---
- name: add APT key...
  become: yes
  become_user: root
  with_items: '{{ gitlab_key_urls }}'
  apt_key:
    url: '{{ item }}'
    state: present

- name: install pkg...
  become: yes
  become_user: root
  apt:
    deb: /tmp/{{ gitlab_pkg }}
