---
- name: Add APT key...
  become: true
  become_user: root
  with_items: '{{ gitlab_key_urls }}'
  ansible.builtin.apt_key:
    url: '{{ item }}'
    state: present

- name: APT installing {{ gitlab_local_pkg }}...
  become: true
  become_user: root
  ansible.builtin.apt:
    deb: '{{ gitlab_local_pkg }}'
