---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_pkg_mgr }}.yml'
      paths:
        - '{{ role_path }}/vars'

- name: install pkg deps...
  become: yes
  become_user: root
  with_items: '{{ gitlab_os_dep_pkgs | default([]) }}'
  package:
    name: '{{ item }}'
    state: present

- name: mkdir -p {{ gitlab_pkg_dir }}
  become: yes
  become_user: root
  file:
    path: '{{ gitlab_pkg_dir }}'
    mode: 0755
    state: directory

- name: looking for {{ gitlab_local_pkg }}...
  become: yes
  stat:
    path: '{{ gitlab_local_pkg }}'
  changed_when: False
  register: gitlab_local_pkg_binary

- when: not gitlab_local_pkg_binary.stat.exists
  block:
    - name: downloading {{ gitlab_pkg_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ gitlab_pkg_url }}'
        dest: '{{ gitlab_local_pkg }}'
        mode: 0700
        timeout: '{{ gitlab_download_timeout_seconds }}'
    - include_tasks: '{{ ansible_pkg_mgr }}.yml'

- when: gitlab_tls.enable
  block:
    - name: mkdir -p {{ gitlab_tls_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ gitlab_tls_dir }}'
        state: directory
        mode: 0755
    - name: install keys/certs
      include_role:
        name: andrewrothstein.tls
      vars:
        tls_become: yes
        tls_become_user: root
        tls_src: '{{ gitlab_tls.pki_dir }}'
        tls_dest: '{{ gitlab_tls_dir }}'
        tls_dest_chmod:
          owner: root
          grp: root

- name: configure gitlab
  when: gitlab_config is defined
  become: yes
  become_user: root
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    mode: 0644
  notify: gitlab_reconfigure
