---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"
    
- name: install pkg deps...
  become: yes
  become_user: root
  with_items: '{{gitlab_os_dep_pkgs}}'
  package: name={{item}} state=present

- name: get bootstrap script...
  become: yes
  become_user: root
  get_url: >-
    url={{gitlab_script}}
    dest=/tmp/gitlab-omnibus-bootstrap.sh
    mode=0755

- name: run bootstrap...
  become: yes
  become_user: root
  command: /tmp/gitlab-omnibus-bootstrap.sh
  args:
    creates: /opt/gitlab/bin/gitlab-ctl

- name: install pkg
  become: yes
  become_user: root
  with_items:
    - gitlab-ce
  package: name={{item}} state=present
