---
- name: Installing andrewrothstein.curl
  ansible.builtin.include_role:
    name: andrewrothstein.curl
- name: Installing andrewrothstein.ca_certs
  ansible.builtin.include_role:
    name: andrewrothstein.ca_certs
- name: Installing andrewrothstein.gpg
  ansible.builtin.include_role:
    name: andrewrothstein.gpg
- name: Installing andrewrothstein.tls
  ansible.builtin.include_role:
    name: andrewrothstein.tls

- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_pkg_mgr }}.yml'
      paths:
        - '{{ role_path }}/vars'

- name: Install pkg deps...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ gitlab_os_dep_pkgs | default([]) }}'
    state: present

- name: Mkdir -p {{ gitlab_pkg_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ gitlab_pkg_dir }}'
    mode: '755'
    state: directory

- name: Looking for {{ gitlab_local_pkg }}...
  become: true
  ansible.builtin.stat:
    path: '{{ gitlab_local_pkg }}'
  changed_when: false
  register: gitlab_local_pkg_binary

- name: Downloading and installing gitlab
  when: not gitlab_local_pkg_binary.stat.exists
  block:
    - name: Downloading {{ gitlab_pkg_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ gitlab_pkg_url }}'
        dest: '{{ gitlab_local_pkg }}'
        mode: '700'
        timeout: '{{ gitlab_download_timeout_seconds }}'
    - name: Installing with {{ ansible_pkg_mgr }}
      ansible.builtin.include_tasks: '{{ ansible_pkg_mgr }}.yml'

- name: Configuring TLS...
  when: gitlab_tls.enable
  block:
    - name: Mkdir -p {{ gitlab_tls_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ gitlab_tls_dir }}'
        state: directory
        mode: '755'
    - name: Install keys/certs
      ansible.builtin.include_role:
        name: andrewrothstein.tls
      vars:
        tls_become: true
        tls_become_user: root
        tls_src: '{{ gitlab_tls.pki_dir }}'
        tls_dest: '{{ gitlab_tls_dir }}'
        tls_dest_chmod:
          owner: root
          grp: root

- name: Configure gitlab
  when: gitlab_config is defined
  become: true
  become_user: root
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    mode: '644'
  notify: Gitlab_reconfigure
