---
- name: RedHat install...
  when: gitlab_install and ansible_os_family == 'RedHat'
  include: RedHat.yml

- name: Debian install...
  when: gitlab_install and ansible_os_family == 'Debian'
  include: Debian.yml

- name: restoring...
  when: gitlab_restore and gitlab_restore_ts is defined
  include: restore.yml
  
- name: backing up...
  when: gitlab_backup
  include: backup.yml

- name: vaulting...
  when: gitlab_vault
  include: vault.yml