---
- name: install /etc/gitlab stuffs...
  command: cp {{gitlab_backups_vault}}/{{gitlab_ts}}/{{item}} /etc/gitlab
  with_items:
    - gitlab.rb
    - gitlab-secrets.json

- name: reconfigure...
  command: gitlab-ctl reconfigure
    
- name: link backup tar...
  file: >
    src={{gitlab_backups_vault}}/{{gitlab_ts}}/{{gitlab_data_tar}}
    dest={{gitlab_backups_dir}}/{{gitlab_data_tar}}
    state=link
    mode=0644
    owner=git

- name: stop unicorn...
  command: gitlab-ctl stop unicorn

- name: stop sidekiq...
  command: gitlab-ctl stop sidekiq

- name: restore backup...
  command: gitlab-rake gitlab:backup:restore BACKUP={{gitlab_ts}} force=yes

- name: restarting gitlab...
  command: gitlab-ctl start
  
